import argparse
import json
import os
import warnings

warnings.filterwarnings("ignore")
os.environ["TF_CPP_MIN_LOG_LEVEL"] = "3"

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import numpy as np

# ── sklearn metrics ───────────────────────────────────────────────────────────
from sklearn.metrics import (
    ConfusionMatrixDisplay,
    accuracy_score,
    average_precision_score,
    classification_report,
    confusion_matrix,
    f1_score,
    precision_recall_curve,
    precision_score,
    recall_score,
    roc_auc_score,
    roc_curve,
)
from sklearn.model_selection import train_test_split

# ── project imports ───────────────────────────────────────────────────────────
import sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from pipeline_utils import (
    GLOBAL_BINS,
    LOCAL_BINS,
    SYNTHETIC_DATA_DIR,
    SYNTHETIC_RESULTS_DIR,
    ensure_project_dirs,
)

import tensorflow as tf

# ── output directory ──────────────────────────────────────────────────────────
BASE_DIR    = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
EVAL_DIR    = os.path.join(BASE_DIR, "results", "evaluation")
os.makedirs(EVAL_DIR, exist_ok=True)

# ── class names (must match generate_dataset.py CLASS_CYCLE order) ────────────
CLASS_NAMES = ["planet_small", "planet_large", "eclipsing_binary",
               "stellar_variability", "noise"]
BINARY_LABEL = {0: "Not Planet", 1: "Planet"}


# ══════════════════════════════════════════════════════════════════════════════
# HELPERS
# ══════════════════════════════════════════════════════════════════════════════

def load_data(data_dir: str):
    """
    Load the saved numpy arrays.  Expects:
      X_global.npy  — shape (N, GLOBAL_BINS)
      X_local.npy   — shape (N, LOCAL_BINS)
      y_train.npy   — binary labels  (N,)
      y_class.npy   — per-class labels (N,)  [optional, generated by new dataset script]

    The holdout split uses the same random_state=42 as train_model.py so the
    validation set here is identical to what the model never saw during training.
    """
    print("  Loading dataset arrays...")
    X_global = np.load(os.path.join(data_dir, "X_global.npy"))
    X_local  = np.load(os.path.join(data_dir, "X_local.npy"))
    y_binary = np.load(os.path.join(data_dir, "y_train.npy"))

    # Per-class labels — optional (generate_dataset.py saves them as y_class.npy)
    class_path = os.path.join(data_dir, "y_class.npy")
    y_class = np.load(class_path) if os.path.exists(class_path) else None

    print(f"  Total samples: {len(y_binary)}")
    print(f"  Class distribution: {dict(zip(*np.unique(y_binary, return_counts=True)))}")

    # Reproduce the exact same 80/20 split used during training
    if y_class is not None:
        _, X_g_val, _, X_l_val, _, y_val, _, y_class_val = train_test_split(
            X_global, X_local, y_binary, y_class,
            test_size=0.2, random_state=42, stratify=y_binary
        )
    else:
        _, X_g_val, _, X_l_val, _, y_val = train_test_split(
            X_global, X_local, y_binary,
            test_size=0.2, random_state=42, stratify=y_binary
        )
        y_class_val = None

    print(f"  Validation set: {len(y_val)} samples")
    return X_g_val, X_l_val, y_val, y_class_val


def load_model(model_path: str):
    print(f"  Loading model from {model_path}...")
    return tf.keras.models.load_model(model_path)


# ══════════════════════════════════════════════════════════════════════════════
# PLOT FUNCTIONS
# ══════════════════════════════════════════════════════════════════════════════

def plot_confusion_matrix(y_true, y_pred, save_dir: str) -> str:
    cm = confusion_matrix(y_true, y_pred)
    fig, ax = plt.subplots(figsize=(6, 5))
    disp = ConfusionMatrixDisplay(
        confusion_matrix=cm,
        display_labels=["Not Planet", "Planet"]
    )
    disp.plot(ax=ax, colorbar=True, cmap="Blues")
    ax.set_title("Confusion Matrix — Validation Set", fontsize=13)

    # Annotate with counts + percentages
    total = cm.sum()
    for text_obj, val in zip(disp.text_.ravel(), cm.ravel()):
        text_obj.set_text(f"{val}\n({val/total*100:.1f}%)")

    plt.tight_layout()
    path = os.path.join(save_dir, "confusion_matrix.png")
    plt.savefig(path, dpi=150)
    plt.close(fig)
    return path


def plot_roc_curve(y_true, y_scores, roc_auc: float, save_dir: str) -> str:
    fpr, tpr, thresholds = roc_curve(y_true, y_scores)

    fig, ax = plt.subplots(figsize=(7, 6))
    ax.plot(fpr, tpr, lw=2, color="#3a7fc1", label=f"ROC curve (AUC = {roc_auc:.4f})")
    ax.plot([0, 1], [0, 1], "k--", lw=1, label="Random classifier")
    ax.fill_between(fpr, tpr, alpha=0.12, color="#3a7fc1")

    # Mark operating point at threshold=0.5
    idx_05 = int(np.argmin(np.abs(thresholds - 0.5)))
    ax.scatter(fpr[idx_05], tpr[idx_05], zorder=5, s=80, color="#c45c5c",
               label=f"Threshold=0.5  (FPR={fpr[idx_05]:.3f}, TPR={tpr[idx_05]:.3f})")

    ax.set_xlabel("False Positive Rate", fontsize=12)
    ax.set_ylabel("True Positive Rate (Recall)", fontsize=12)
    ax.set_title("ROC Curve — Exoplanet Detection", fontsize=13)
    ax.legend(fontsize=10)
    ax.set_xlim([-0.02, 1.02])
    ax.set_ylim([-0.02, 1.05])
    ax.grid(alpha=0.3)

    plt.tight_layout()
    path = os.path.join(save_dir, "roc_curve.png")
    plt.savefig(path, dpi=150)
    plt.close(fig)
    return path


def plot_pr_curve(y_true, y_scores, pr_auc: float, save_dir: str) -> str:
    precision_vals, recall_vals, thresholds = precision_recall_curve(y_true, y_scores)
    baseline = float(y_true.sum()) / len(y_true)

    fig, ax = plt.subplots(figsize=(7, 6))
    ax.plot(recall_vals, precision_vals, lw=2, color="#4caf50",
            label=f"PR curve (AP = {pr_auc:.4f})")
    ax.axhline(baseline, color="gray", lw=1, ls="--",
               label=f"Baseline (positive rate = {baseline:.3f})")
    ax.fill_between(recall_vals, precision_vals, alpha=0.12, color="#4caf50")

    # Mark threshold=0.5
    idx_05 = int(np.argmin(np.abs(thresholds - 0.5)))
    ax.scatter(recall_vals[idx_05], precision_vals[idx_05], zorder=5, s=80,
               color="#c45c5c",
               label=f"Threshold=0.5  (R={recall_vals[idx_05]:.3f}, P={precision_vals[idx_05]:.3f})")

    ax.set_xlabel("Recall", fontsize=12)
    ax.set_ylabel("Precision", fontsize=12)
    ax.set_title("Precision-Recall Curve — Exoplanet Detection", fontsize=13)
    ax.legend(fontsize=10)
    ax.set_xlim([-0.02, 1.02])
    ax.set_ylim([0.0, 1.05])
    ax.grid(alpha=0.3)

    plt.tight_layout()
    path = os.path.join(save_dir, "pr_curve.png")
    plt.savefig(path, dpi=150)
    plt.close(fig)
    return path


def plot_per_class_breakdown(y_class, y_true, y_scores, save_dir: str) -> str:
    """
    For each of the 5 synthetic classes, plot the distribution of model
    confidence scores as a histogram.  This immediately shows whether the
    model confuses eclipsing binaries with planets, etc.
    """
    if y_class is None:
        print("  y_class.npy not found — skipping per-class breakdown plot.")
        return ""

    # Map numeric class ids back to names
    # CLASS_CYCLE order: planet_small=0, planet_large=1, eb=2, variability=3, noise=4
    # but generate_dataset.py cycles through them by index, so class label == index % 5
    class_id_to_name = {i: name for i, name in enumerate(CLASS_NAMES)}

    fig, axes = plt.subplots(1, len(CLASS_NAMES), figsize=(18, 4), sharey=False)
    fig.suptitle("Model Confidence Distribution by Signal Class", fontsize=13)

    colors = ["#4caf50", "#2196f3", "#f44336", "#ff9800", "#9e9e9e"]

    for ax, (cls_id, cls_name), color in zip(axes, class_id_to_name.items(), colors):
        mask = (y_class == cls_id)
        if mask.sum() == 0:
            ax.set_title(f"{cls_name}\n(no samples)")
            continue
        scores = y_scores[mask]
        ax.hist(scores, bins=30, color=color, alpha=0.8, edgecolor="white", lw=0.3)
        ax.axvline(0.5, color="red", lw=1.5, ls="--", label="Threshold")
        frac_above = float((scores >= 0.5).mean())
        ax.set_title(
            f"{cls_name}\n"
            f"n={mask.sum()}   "
            f"{'Detected' if cls_id < 2 else 'Flagged'}: {frac_above:.1%}",
            fontsize=9
        )
        ax.set_xlabel("Model confidence", fontsize=8)
        ax.set_ylabel("Count", fontsize=8)
        ax.set_xlim(0, 1)
        ax.legend(fontsize=7)

    plt.tight_layout()
    path = os.path.join(save_dir, "per_class_confidence.png")
    plt.savefig(path, dpi=150)
    plt.close(fig)
    return path


def plot_combined_summary(y_true, y_pred, y_scores, metrics: dict, save_dir: str) -> str:
    """
    Single-page 2×2 summary figure — the one you want in your presentation slide.
    """
    fig = plt.figure(figsize=(14, 10))
    fig.suptitle(
        f"Exoplanet Detection Model — Validation Evaluation\n"
        f"Accuracy {metrics['accuracy']:.3f}  |  "
        f"Precision {metrics['precision']:.3f}  |  "
        f"Recall {metrics['recall']:.3f}  |  "
        f"F1 {metrics['f1']:.3f}  |  "
        f"ROC-AUC {metrics['roc_auc']:.4f}  |  "
        f"PR-AUC {metrics['pr_auc']:.4f}",
        fontsize=11, y=0.99
    )

    gs = gridspec.GridSpec(2, 2, figure=fig, hspace=0.38, wspace=0.32)

    # ── Confusion matrix ─────────────────────────────────────────────────────
    ax1 = fig.add_subplot(gs[0, 0])
    cm = confusion_matrix(y_true, y_pred)
    ConfusionMatrixDisplay(cm, display_labels=["Not Planet", "Planet"]).plot(
        ax=ax1, colorbar=False, cmap="Blues"
    )
    ax1.set_title("Confusion Matrix")

    # ── Score distribution ────────────────────────────────────────────────────
    ax2 = fig.add_subplot(gs[0, 1])
    ax2.hist(y_scores[y_true == 0], bins=40, color="#3a7fc1", alpha=0.7, label="Not Planet")
    ax2.hist(y_scores[y_true == 1], bins=40, color="#c45c5c", alpha=0.7, label="Planet")
    ax2.axvline(0.5, color="black", lw=1.5, ls="--", label="Threshold")
    ax2.set_xlabel("Model confidence score")
    ax2.set_ylabel("Count")
    ax2.set_title("Confidence Score Distribution")
    ax2.legend(fontsize=9)

    # ── ROC ───────────────────────────────────────────────────────────────────
    ax3 = fig.add_subplot(gs[1, 0])
    fpr, tpr, _ = roc_curve(y_true, y_scores)
    ax3.plot(fpr, tpr, lw=2, color="#3a7fc1", label=f"AUC = {metrics['roc_auc']:.4f}")
    ax3.plot([0, 1], [0, 1], "k--", lw=1)
    ax3.fill_between(fpr, tpr, alpha=0.12, color="#3a7fc1")
    ax3.set_xlabel("False Positive Rate")
    ax3.set_ylabel("True Positive Rate")
    ax3.set_title("ROC Curve")
    ax3.legend(fontsize=10)
    ax3.grid(alpha=0.3)

    # ── PR ────────────────────────────────────────────────────────────────────
    ax4 = fig.add_subplot(gs[1, 1])
    precision_vals, recall_vals, _ = precision_recall_curve(y_true, y_scores)
    baseline = float(y_true.sum()) / len(y_true)
    ax4.plot(recall_vals, precision_vals, lw=2, color="#4caf50", label=f"AP = {metrics['pr_auc']:.4f}")
    ax4.axhline(baseline, color="gray", lw=1, ls="--", label="Baseline")
    ax4.fill_between(recall_vals, precision_vals, alpha=0.12, color="#4caf50")
    ax4.set_xlabel("Recall")
    ax4.set_ylabel("Precision")
    ax4.set_title("Precision-Recall Curve")
    ax4.legend(fontsize=10)
    ax4.grid(alpha=0.3)

    path = os.path.join(save_dir, "combined_summary.png")
    plt.savefig(path, dpi=150, bbox_inches="tight")
    plt.close(fig)
    return path


def main():
    parser = argparse.ArgumentParser(description="Evaluate the trained Exoplanet detection model.")
    parser.add_argument("--data-dir", type=str, default=SYNTHETIC_DATA_DIR,
                        help="Path to dataset numpy arrays.")
    parser.add_argument("--model-path", type=str,
                        default=os.path.join(SYNTHETIC_RESULTS_DIR, "exoplanet_cnn_model.keras"),
                        help="Path to trained keras model.")
    args = parser.parse_args()

    ensure_project_dirs()

    print(f"\n{'='*60}")
    print("  EXOPLANET MODEL EVALUATION")
    print(f"{'='*60}")

    if not os.path.exists(args.model_path):
        print(f"Error: Model not found at {args.model_path}")
        return
    if not os.path.exists(os.path.join(args.data_dir, "X_global.npy")):
        print(f"Error: Dataset not found in {args.data_dir}")
        return

    X_g_val, X_l_val, y_val, y_class_val = load_data(args.data_dir)
    model = load_model(args.model_path)

    print("\n  Running inference...")
    y_scores = model.predict([X_g_val, X_l_val], batch_size=64).flatten()
    y_pred = (y_scores >= 0.5).astype(int)

    print("  Calculating metrics...")
    acc = accuracy_score(y_val, y_pred)
    prec = precision_score(y_val, y_pred, zero_division=0)
    rec = recall_score(y_val, y_pred, zero_division=0)
    f1 = f1_score(y_val, y_pred, zero_division=0)
    try:
        roc_auc = roc_auc_score(y_val, y_scores)
    except ValueError:
        roc_auc = 0.0
    pr_auc = average_precision_score(y_val, y_scores)

    metrics = {
        "accuracy": float(acc),
        "precision": float(prec),
        "recall": float(rec),
        "f1": float(f1),
        "roc_auc": float(roc_auc),
        "pr_auc": float(pr_auc),
    }

    print("\n  Classification Report:")
    print(classification_report(y_val, y_pred, target_names=["Not Planet", "Planet"]))

    print(f"\n  ROC-AUC: {roc_auc:.4f}")
    print(f"  PR-AUC:  {pr_auc:.4f}")

    print("\n  Generating plots...")
    plot_confusion_matrix(y_val, y_pred, EVAL_DIR)
    plot_roc_curve(y_val, y_scores, roc_auc, EVAL_DIR)
    plot_pr_curve(y_val, y_scores, pr_auc, EVAL_DIR)
    plot_per_class_breakdown(y_class_val, y_val, y_scores, EVAL_DIR)
    plot_combined_summary(y_val, y_pred, y_scores, metrics, EVAL_DIR)

    json_path = os.path.join(EVAL_DIR, "evaluation_metrics.json")
    with open(json_path, "w") as f:
        json.dump(metrics, f, indent=4)

    print(f"\n  Done! Evaluation results saved to: {EVAL_DIR}")


if __name__ == "__main__":
    main()
